version: '3.8'

services:
  postgres:
    image: postgres:13.4
    volumes:
      - almograve_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=almograve
      - POSTGRES_PASSWORD=surftheworld
      - POSTGRES_DB=almograve
    ports:
      - 5433:5432

volumes:
  almograve_data:
