[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=. --cov-report term-missing --verbose --reuse-db --durations=3"
python_files = ["tests.py"]
DJANGO_SETTINGS_MODULE = "almograve.settings"
