[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=. --cov-report term-missing --verbose --reuse-db --durations=3"
python_files = ["tests.py"]
DJANGO_SETTINGS_MODULE = "almograve.settings"

[tool.mypy]
python_version = "3.11"
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = "true"

[tool.django-stubs]
django_settings_module = "almograve.settings"

[tool.djlint]
ignore="H021"
extend_exclude=".venv,.vscode,.git,.github,htmlcov"

[tool.ruff]
line-length = 140
exclude = [
    ".venv",
    ".vscode",
    ".git",
    ".github",
    "htmlcov",
]
target-version = "py311"
fix = true
