# Generated by Django 3.2.7 on 2021-09-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["date_created"]},
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["date_created"]},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["date_created"]},
        ),
        migrations.AlterModelOptions(
            name="result",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="board",
            name="date_deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="date_deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="date_deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["date_deleted", "user", "date_created"],
                name="goals_board_date_de_0e2f98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["date_deleted", "group", "date_created"],
                name="goals_goal_date_de_319394_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["date_deleted", "board", "date_created"],
                name="goals_group_date_de_139887_idx",
            ),
        ),
    ]
