# Generated by Django 3.2.7 on 2021-09-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_auto_20210922_2004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="change_amount",
        ),
        migrations.AddField(
            model_name="event",
            name="new_amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="old_amount",
            field=models.IntegerField(null=True),
        ),
    ]
