# Generated by Django 3.2.8 on 2021-10-16 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0004_auto_20210925_0155"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date_event",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE goals_event SET date_event = date_created"),
    ]
