name: Upgrade dependencies

on:
  schedule:
  - cron: "0 6 * * 6"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Run pipenv lock --dev
      run: |
        pipenv lock --dev
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update dependencies
        branch: bot/update_dependencies
        delete-branch: true
        title: 'Update dependencies'
        body: |
          Updating project dependencies.
        reviewers: anze3db
