name: Upgrade dependencies

on:
  schedule:
  - cron: "0 6 1 * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Set up uv
      # Install latest uv version using the installer
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Upgrade dependencies 
      run: |
        uv sync --upgrade
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update dependencies
        branch: bot/update_dependencies
        delete-branch: true
        title: 'Update dependencies'
        body: |
          Updating project dependencies.
        reviewers: anze3db
